cc_binary(
    name = "data_access",
    srcs = [
        "data_access.cc",
    ],
)

cc_binary(
    name = "phone_keypad_cpp",
    srcs = [
        "phone_keypad.cc",
    ],
)

py_binary(
    name = "phone_keypad",
    srcs = [
        "phone_keypad.py",
    ],
    python_version = "PY3",
)
