cc_binary(
    name = "bit_field",
    srcs = [
        "bit_field.cc",
    ],
)

cc_binary(
    name = "pointer_cast",
    srcs = [
        "pointer_cast.cc",
    ],
)

cc_binary(
    name = "reverse_bits",
    srcs = [
        "reverse_bits.cc",
    ],
)
