cc_binary(
    name = "initial_list",
    srcs = [
        "initial_list.cc",
    ],
)

cc_binary(
    name = "rand_list_copy",
    srcs = [
        "rand_list_copy.cc",
    ],
)

cc_binary(
    name = "reverse_list",
    srcs = [
        "reverse_list.cc",
    ],
)

cc_binary(
    name = "weak_ptr",
    srcs = [
        "weak_ptr.cc",
    ],
)
